#!/usr/bin/env bash
set -euo pipefail

: "${DATABASE_URL:?DATABASE_URL must be set to a disposable PostgreSQL database}"

REPORT_FILE="${VERIFICATION_REPORT_FILE:-verification-report.md}"

run_step() {
  local title="$1"
  shift

  echo "==> ${title}"
  "$@"
  printf -- '- ✅ %s\n' "$title" >> "$REPORT_FILE"
}

cat > "$REPORT_FILE" <<'EOF'
# Backend Verification Report

This report is generated by `backend/scripts/verify_backend.sh`.

## Results
EOF

run_step "Compile backend application" python -m compileall -q app
run_step "Compile Alembic migrations" python -m compileall -q migrations
run_step "Upgrade clean database to Alembic head" python -m alembic upgrade head
run_step "Confirm current Alembic revision" python -m alembic current
run_step "Check model and database schema drift" python -m alembic check
run_step "Downgrade database to base" python -m alembic downgrade base
run_step "Re-upgrade database to Alembic head" python -m alembic upgrade head
run_step "Run backend test suite" python -m pytest -q ../tests

cat >> "$REPORT_FILE" <<'EOF'

## Evidence Level

All commands above completed successfully in this environment. This report does not prove VPS or production deployment behavior.
EOF

echo "Backend verification completed successfully."
echo "Report: $REPORT_FILE"
