events {}

http {
    server {
        listen 80;
        server_name _;

        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /admin/ {
            proxy_pass http://admin-panel/;
            proxy_set_header Host $host;
        }

        location /app/ {
            proxy_pass http://mini-app/;
            proxy_set_header Host $host;
        }
    }
}
